services:
  - type: web
    name: detroitaxle-typesense-haproxy
    runtime: docker
    plan: pro max

    healthCheckPath: /health

    envVars:
      - key: TYPESENSE_BACKENDS
        value: detroitaxle-typesense-production:8108,detroitaxle-typesense-production-2:8108
